### ISSUE TITLE
Date-based Scheduling is always triggered!

### ISSUE THREAD

**Issue by harishvc** [mattpat/node-schedule#36]
Date-based scheduling example in the README document is triggered all the time (irrespective of the time set). Maybe I am not properly implementing. Could you please assist further?

**Comment by onaclov2000** [comment]
As a side note if you do a console.log(date); I am noticing that my months are off, it appears 0 based (which may not be helpful) I thought I read somewhere that anything over a month (maybe?) wasn't scheduling right, so one thing to look at is whether the month is the one you are expecting, for example, 

    var temp = new Date(2015, 1, 5, 23, 31, 0);

Is actually February according to my system, and changing the months to 0 puts me back in January.

This may or may not help others, but I wanted to mention it since i found it surprising/confusing.

(also the hours is in 24 hour format, which messed me up for a bit).

**Comment by yozef** [comment]
ummmm... This is my trace: Executes every second...
2015/02/04 20:43:00.566 +00:00 [DEBUG] [11685] CronJob got executed - Dated For: Fri Feb 06 2015 15:42:12 GMT-0500 (EST)
2015/02/04 20:44:00.574 +00:00 [DEBUG] [11685] CronJob got executed - Dated For: Fri Feb 06 2015 15:42:12 GMT-0500 (EST)
2015/02/04 20:45:00.572 +00:00 [DEBUG] [11685] CronJob got executed - Dated For: Fri Feb 06 2015 15:42:12 GMT-0500 (EST)

**Comment by tejasmanohar** [comment]
Merged :)
